{"name": "test_accept_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'access'", "trace": "self = <test_db.TestMysql object at 0x000001F935FDFEE0>\n\n>   ???\nE   AttributeError: 'NoneType' object has no attribute 'access'\n\nD:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\tests\\db_test\\test_db.py:77: AttributeError"}, "start": 1640027052114, "stop": 1640027052279, "uuid": "16eda858-97c3-4764-8026-67f91c671430", "historyId": "11273d533fc76839336a35fa0fc173a3", "testCaseId": "e340fb0e57b7bc8c4acadf3f570a45ce", "fullName": "tests.db_test.test_db.TestMysql#test_accept_user", "labels": [{"name": "story", "value": "Accept user"}, {"name": "feature", "value": "DB tests"}, {"name": "epic", "value": "Awesome test application"}, {"name": "parentSuite", "value": "tests.db_test"}, {"name": "suite", "value": "test_db"}, {"name": "subSuite", "value": "TestMysql"}, {"name": "host", "value": "DESKTOP-LERA"}, {"name": "thread", "value": "2648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.db_test.test_db"}]}