{"name": "test_block_blocked_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'access'", "trace": "self = <test_db.TestMysql object at 0x000001BAFB30F9A0>\n\n    @allure.epic('Awesome test application')\n    @allure.feature('DB tests')\n    @allure.story('Block user')\n    def test_block_blocked_user(self):\n        block_user = TestUser(\n            username=\"blockuser2\",\n            password=\"1234\",\n            email=\"blockuser2@test.ru\"\n        )\n        self.api_client.create_user(block_user.username, block_user.password, block_user.email)\n        self.api_client.block_user(block_user.username)\n        self.api_client.block_user(block_user.username)\n        found_user = self.mysql.session.query(TestUser) \\\n            .filter(TestUser.username == block_user.username) \\\n            .filter(TestUser.password == block_user.password) \\\n            .filter(TestUser.email == block_user.email).first()\n>       assert found_user.access == 0\nE       AttributeError: 'NoneType' object has no attribute 'access'\n\ntests\\db_test\\test_db.py:97: AttributeError"}, "start": 1640010802085, "stop": 1640010802194, "uuid": "1ed77452-3c3d-4166-845a-ac2eed2e28be", "historyId": "f81301c65d01367a63f12ad31b5b5da3", "testCaseId": "88f63d622d10e1aa9841323ba1733298", "fullName": "tests.db_test.test_db.TestMysql#test_block_blocked_user", "labels": [{"name": "feature", "value": "DB tests"}, {"name": "story", "value": "Block user"}, {"name": "epic", "value": "Awesome test application"}, {"name": "parentSuite", "value": "tests.db_test"}, {"name": "suite", "value": "test_db"}, {"name": "subSuite", "value": "TestMysql"}, {"name": "host", "value": "DESKTOP-LERA"}, {"name": "thread", "value": "6588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.db_test.test_db"}]}